// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/service/route/v3/rds.proto

package io.envoyproxy.envoy.service.route.v3;

/**
 * <pre>
 * Virtual Host Discovery Service (VHDS) is used to dynamically update the list of virtual hosts for
 * a given RouteConfiguration. If VHDS is configured a virtual host list update will be triggered
 * during the processing of an HTTP request if a route for the request cannot be resolved. The
 * :ref:`resource_names_subscribe &lt;envoy_api_field_service.discovery.v3.DeltaDiscoveryRequest.resource_names_subscribe&gt;`
 * field contains a list of virtual host names or aliases to track. The contents of an alias would
 * be the contents of a *host* or *authority* header used to make an http request. An xDS server
 * will match an alias to a virtual host based on the content of :ref:`domains'
 * &lt;envoy_api_field_config.route.v3.VirtualHost.domains&gt;` field. The *resource_names_unsubscribe* field
 * contains a list of virtual host names that have been :ref:`unsubscribed
 * &lt;xds_protocol_unsubscribe&gt;` from the routing table associated with the RouteConfiguration.
 * </pre>
 *
 * Protobuf service {@code envoy.service.route.v3.VirtualHostDiscoveryService}
 */
public  abstract class VirtualHostDiscoveryService
    implements com.google.protobuf.Service {
  protected VirtualHostDiscoveryService() {}

  public interface Interface {
    /**
     * <code>rpc DeltaVirtualHosts(stream .envoy.service.discovery.v3.DeltaDiscoveryRequest) returns (stream .envoy.service.discovery.v3.DeltaDiscoveryResponse);</code>
     */
    public abstract void deltaVirtualHosts(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request,
        com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new VirtualHostDiscoveryService() {
      @java.lang.Override
      public  void deltaVirtualHosts(
          com.google.protobuf.RpcController controller,
          io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request,
          com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse> done) {
        impl.deltaVirtualHosts(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.deltaVirtualHosts(controller, (io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc DeltaVirtualHosts(stream .envoy.service.discovery.v3.DeltaDiscoveryRequest) returns (stream .envoy.service.discovery.v3.DeltaDiscoveryResponse);</code>
   */
  public abstract void deltaVirtualHosts(
      com.google.protobuf.RpcController controller,
      io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request,
      com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return io.envoyproxy.envoy.service.route.v3.RdsProto.getDescriptor().getServices().get(1);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.deltaVirtualHosts(controller, (io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest)request,
          com.google.protobuf.RpcUtil.<io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends io.envoyproxy.envoy.service.route.v3.VirtualHostDiscoveryService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void deltaVirtualHosts(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request,
        com.google.protobuf.RpcCallback<io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.class,
          io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse deltaVirtualHosts(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse deltaVirtualHosts(
        com.google.protobuf.RpcController controller,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryRequest request)
        throws com.google.protobuf.ServiceException {
      return (io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        io.envoyproxy.envoy.service.discovery.v3.DeltaDiscoveryResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:envoy.service.route.v3.VirtualHostDiscoveryService)
}

