version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - java-ratelimit-network

  envoy-proxy:
    image: envoyproxy/envoy:v1.18-latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/proxy-my.yaml:/etc/envoy/envoy.yaml
    networks:
      - java-ratelimit-network
    expose:
      - "8888"
      - "8001"
      - "10000"
      - "8887"
      - "8889"
    ports:
      - "8888:8888"
      - "8001:8001"
      - "10000:10000"
      - "8887:8887"
      - "8889:8889"

  envoy-mock:
    image: envoyproxy/envoy:v1.18-latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/mock.yaml:/etc/envoy/envoy.yaml
    networks:
      - java-ratelimit-network
    expose:
      - "9999"
    ports:
      - "9999:9999"
networks:
  java-ratelimit-network:
