version: "3"
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - java-ratelimit-network

  # minimal container that builds the ratelimit service binary and exits.
#  ratelimit-build:
#    image: golang:1.14-alpine
#    working_dir: /go/src/github.com/envoyproxy/ratelimit
#    command: go build -o /usr/local/bin/ratelimit ./src/service_cmd/main.go
#    volumes:
#      - .:/go/src/github.com/envoyproxy/ratelimit
#      - binary:/usr/local/bin/
#
#  ratelimit-client-build:
#    image: golang:1.14-alpine
#    working_dir: /go/src/github.com/envoyproxy/ratelimit
#    command: go build -o /usr/local/bin/ratelimit_client ./src/client_cmd/main.go
#    volumes:
#      - .:/go/src/github.com/envoyproxy/ratelimit
#      - binary:/usr/local/bin/
#
  java-ratelimit:
    image: openjdk:8u292-jre-slim
    working_dir: /opt/ratelimit/
    command: java -jar /opt/ratelimit/grpc-server-all.jar
    expose:
      - "8082"
    ports:
      - 8082:8082
    depends_on:
      - redis
    networks:
      - java-ratelimit-network
    volumes:
      - ./grpc-server/build/libs:/opt/ratelimit/

  envoy-proxy:
    image: envoyproxy/envoy:v1.18-latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/proxy-my.yaml:/etc/envoy/envoy.yaml
    networks:
      - java-ratelimit-network
    expose:
      - "8888"
      - "8001"
      - "10000"
      - "8887"
      - "8889"
    ports:
      - "8888:8888"
      - "8001:8001"
      - "10000:10000"
      - "8887:8887"
      - "8889:8889"

  envoy-mock:
    image: envoyproxy/envoy:v1.18-latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./examples/envoy/mock.yaml:/etc/envoy/envoy.yaml
    networks:
      - java-ratelimit-network
    expose:
      - "9999"
    ports:
      - "9999:9999"
networks:
  java-ratelimit-network:
