// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/config/trace/v3/trace.proto

package io.envoyproxy.envoy.config.trace.v3;

public final class TraceProto {
  private TraceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!envoy/config/trace/v3/trace.proto\022\025env" +
      "oy.config.trace.v3\032\035udpa/annotations/sta" +
      "tus.proto\032#envoy/config/trace/v3/datadog" +
      ".proto\032&envoy/config/trace/v3/dynamic_ot" +
      ".proto\032\'envoy/config/trace/v3/http_trace" +
      "r.proto\032%envoy/config/trace/v3/lightstep" +
      ".proto\032&envoy/config/trace/v3/opencensus" +
      ".proto\032#envoy/config/trace/v3/service.pr" +
      "oto\032\"envoy/config/trace/v3/zipkin.protoB" +
      "3\n#io.envoyproxy.envoy.config.trace.v3B\n" +
      "TraceProtoP\001P\001P\002P\003P\004P\005P\006P\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          udpa.annotations.Status.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.DatadogProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.DynamicOtProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.HttpTracerProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.LightstepProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.OpencensusProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.ServiceProto.getDescriptor(),
          io.envoyproxy.envoy.config.trace.v3.ZipkinProto.getDescriptor(),
        });
    udpa.annotations.Status.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.DatadogProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.DynamicOtProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.HttpTracerProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.LightstepProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.OpencensusProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.ServiceProto.getDescriptor();
    io.envoyproxy.envoy.config.trace.v3.ZipkinProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
