// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/config/route/v3/route_components.proto

package io.envoyproxy.envoy.config.route.v3;

public interface WeightedClusterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:envoy.config.route.v3.WeightedCluster)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Specifies one or more upstream clusters associated with the route.
   * </pre>
   *
   * <code>repeated .envoy.config.route.v3.WeightedCluster.ClusterWeight clusters = 1 [(.validate.rules) = { ... }</code>
   */
  java.util.List<io.envoyproxy.envoy.config.route.v3.WeightedCluster.ClusterWeight> 
      getClustersList();
  /**
   * <pre>
   * Specifies one or more upstream clusters associated with the route.
   * </pre>
   *
   * <code>repeated .envoy.config.route.v3.WeightedCluster.ClusterWeight clusters = 1 [(.validate.rules) = { ... }</code>
   */
  io.envoyproxy.envoy.config.route.v3.WeightedCluster.ClusterWeight getClusters(int index);
  /**
   * <pre>
   * Specifies one or more upstream clusters associated with the route.
   * </pre>
   *
   * <code>repeated .envoy.config.route.v3.WeightedCluster.ClusterWeight clusters = 1 [(.validate.rules) = { ... }</code>
   */
  int getClustersCount();
  /**
   * <pre>
   * Specifies one or more upstream clusters associated with the route.
   * </pre>
   *
   * <code>repeated .envoy.config.route.v3.WeightedCluster.ClusterWeight clusters = 1 [(.validate.rules) = { ... }</code>
   */
  java.util.List<? extends io.envoyproxy.envoy.config.route.v3.WeightedCluster.ClusterWeightOrBuilder> 
      getClustersOrBuilderList();
  /**
   * <pre>
   * Specifies one or more upstream clusters associated with the route.
   * </pre>
   *
   * <code>repeated .envoy.config.route.v3.WeightedCluster.ClusterWeight clusters = 1 [(.validate.rules) = { ... }</code>
   */
  io.envoyproxy.envoy.config.route.v3.WeightedCluster.ClusterWeightOrBuilder getClustersOrBuilder(
      int index);

  /**
   * <pre>
   * Specifies the total weight across all clusters. The sum of all cluster weights must equal this
   * value, which must be greater than 0. Defaults to 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value total_weight = 3 [(.validate.rules) = { ... }</code>
   * @return Whether the totalWeight field is set.
   */
  boolean hasTotalWeight();
  /**
   * <pre>
   * Specifies the total weight across all clusters. The sum of all cluster weights must equal this
   * value, which must be greater than 0. Defaults to 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value total_weight = 3 [(.validate.rules) = { ... }</code>
   * @return The totalWeight.
   */
  com.google.protobuf.UInt32Value getTotalWeight();
  /**
   * <pre>
   * Specifies the total weight across all clusters. The sum of all cluster weights must equal this
   * value, which must be greater than 0. Defaults to 100.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value total_weight = 3 [(.validate.rules) = { ... }</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getTotalWeightOrBuilder();

  /**
   * <pre>
   * Specifies the runtime key prefix that should be used to construct the
   * runtime keys associated with each cluster. When the *runtime_key_prefix* is
   * specified, the router will look for weights associated with each upstream
   * cluster under the key *runtime_key_prefix* + "." + *cluster[i].name* where
   * *cluster[i]* denotes an entry in the clusters array field. If the runtime
   * key for the cluster does not exist, the value specified in the
   * configuration file will be used as the default weight. See the :ref:`runtime documentation
   * &lt;operations_runtime&gt;` for how key names map to the underlying implementation.
   * </pre>
   *
   * <code>string runtime_key_prefix = 2;</code>
   * @return The runtimeKeyPrefix.
   */
  java.lang.String getRuntimeKeyPrefix();
  /**
   * <pre>
   * Specifies the runtime key prefix that should be used to construct the
   * runtime keys associated with each cluster. When the *runtime_key_prefix* is
   * specified, the router will look for weights associated with each upstream
   * cluster under the key *runtime_key_prefix* + "." + *cluster[i].name* where
   * *cluster[i]* denotes an entry in the clusters array field. If the runtime
   * key for the cluster does not exist, the value specified in the
   * configuration file will be used as the default weight. See the :ref:`runtime documentation
   * &lt;operations_runtime&gt;` for how key names map to the underlying implementation.
   * </pre>
   *
   * <code>string runtime_key_prefix = 2;</code>
   * @return The bytes for runtimeKeyPrefix.
   */
  com.google.protobuf.ByteString
      getRuntimeKeyPrefixBytes();
}
