// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/service/extension/v3/config_discovery.proto

package io.envoyproxy.envoy.service.extension.v3;

public interface EcdsDummyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:envoy.service.extension.v3.EcdsDummy)
    com.google.protobuf.MessageOrBuilder {
}
