// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/extensions/compression/gzip/decompressor/v3/gzip.proto

package io.envoyproxy.envoy.extensions.compression.gzip.decompressor.v3;

public interface GzipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:envoy.extensions.compression.gzip.decompressor.v3.Gzip)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Value from 9 to 15 that represents the base two logarithmic of the decompressor's window size.
   * The decompression window size needs to be equal or larger than the compression window size.
   * The default window size is 15.
   * This is so that the decompressor can decompress a response compressed by a compressor with any compression window size.
   * For more details about this parameter, please refer to `zlib manual &lt;https://www.zlib.net/manual.html&gt;`_ &gt; inflateInit2.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value window_bits = 1 [(.validate.rules) = { ... }</code>
   * @return Whether the windowBits field is set.
   */
  boolean hasWindowBits();
  /**
   * <pre>
   * Value from 9 to 15 that represents the base two logarithmic of the decompressor's window size.
   * The decompression window size needs to be equal or larger than the compression window size.
   * The default window size is 15.
   * This is so that the decompressor can decompress a response compressed by a compressor with any compression window size.
   * For more details about this parameter, please refer to `zlib manual &lt;https://www.zlib.net/manual.html&gt;`_ &gt; inflateInit2.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value window_bits = 1 [(.validate.rules) = { ... }</code>
   * @return The windowBits.
   */
  com.google.protobuf.UInt32Value getWindowBits();
  /**
   * <pre>
   * Value from 9 to 15 that represents the base two logarithmic of the decompressor's window size.
   * The decompression window size needs to be equal or larger than the compression window size.
   * The default window size is 15.
   * This is so that the decompressor can decompress a response compressed by a compressor with any compression window size.
   * For more details about this parameter, please refer to `zlib manual &lt;https://www.zlib.net/manual.html&gt;`_ &gt; inflateInit2.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value window_bits = 1 [(.validate.rules) = { ... }</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getWindowBitsOrBuilder();

  /**
   * <pre>
   * Value for zlib's decompressor output buffer. If not set, defaults to 4096.
   * See https://www.zlib.net/manual.html for more details.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value chunk_size = 2 [(.validate.rules) = { ... }</code>
   * @return Whether the chunkSize field is set.
   */
  boolean hasChunkSize();
  /**
   * <pre>
   * Value for zlib's decompressor output buffer. If not set, defaults to 4096.
   * See https://www.zlib.net/manual.html for more details.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value chunk_size = 2 [(.validate.rules) = { ... }</code>
   * @return The chunkSize.
   */
  com.google.protobuf.UInt32Value getChunkSize();
  /**
   * <pre>
   * Value for zlib's decompressor output buffer. If not set, defaults to 4096.
   * See https://www.zlib.net/manual.html for more details.
   * </pre>
   *
   * <code>.google.protobuf.UInt32Value chunk_size = 2 [(.validate.rules) = { ... }</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getChunkSizeOrBuilder();
}
