// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto

package io.envoyproxy.envoy.extensions.filters.http.ext_authz.v3;

public final class ExtAuthzProto {
  private ExtAuthzProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthz_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthz_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_BufferSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_BufferSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_HttpService_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_HttpService_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthzPerRoute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthzPerRoute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_ContextExtensionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_ContextExtensionsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:envoy/extensions/filters/http/ext_auth" +
      "z/v3/ext_authz.proto\022*envoy.extensions.f" +
      "ilters.http.ext_authz.v3\032\037envoy/config/c" +
      "ore/v3/base.proto\032(envoy/config/core/v3/" +
      "config_source.proto\032\'envoy/config/core/v" +
      "3/grpc_service.proto\032#envoy/config/core/" +
      "v3/http_uri.proto\032$envoy/type/matcher/v3" +
      "/metadata.proto\032\"envoy/type/matcher/v3/s" +
      "tring.proto\032\037envoy/type/v3/http_status.p" +
      "roto\032#envoy/annotations/deprecation.prot" +
      "o\032\035udpa/annotations/status.proto\032!udpa/a" +
      "nnotations/versioning.proto\032\027validate/va" +
      "lidate.proto\"\247\006\n\010ExtAuthz\0229\n\014grpc_servic" +
      "e\030\001 \001(\0132!.envoy.config.core.v3.GrpcServi" +
      "ceH\000\022O\n\014http_service\030\003 \001(\01327.envoy.exten" +
      "sions.filters.http.ext_authz.v3.HttpServ" +
      "iceH\000\022I\n\025transport_api_version\030\014 \001(\0162 .e" +
      "nvoy.config.core.v3.ApiVersionB\010\372B\005\202\001\002\020\001" +
      "\022\032\n\022failure_mode_allow\030\002 \001(\010\022U\n\021with_req" +
      "uest_body\030\005 \001(\0132:.envoy.extensions.filte" +
      "rs.http.ext_authz.v3.BufferSettings\022\031\n\021c" +
      "lear_route_cache\030\006 \001(\010\0222\n\017status_on_erro" +
      "r\030\007 \001(\0132\031.envoy.type.v3.HttpStatus\022#\n\033me" +
      "tadata_context_namespaces\030\010 \003(\t\022F\n\016filte" +
      "r_enabled\030\t \001(\0132..envoy.config.core.v3.R" +
      "untimeFractionalPercent\022G\n\027filter_enable" +
      "d_metadata\030\016 \001(\0132&.envoy.type.matcher.v3" +
      ".MetadataMatcher\022A\n\017deny_at_disable\030\013 \001(" +
      "\0132(.envoy.config.core.v3.RuntimeFeatureF" +
      "lag\022 \n\030include_peer_certificate\030\n \001(\010\022\023\n" +
      "\013stat_prefix\030\r \001(\t:5\232\305\210\0360\n.envoy.config." +
      "filter.http.ext_authz.v2.ExtAuthzB\n\n\010ser" +
      "vicesJ\004\010\004\020\005R\tuse_alpha\"\247\001\n\016BufferSetting" +
      "s\022\"\n\021max_request_bytes\030\001 \001(\rB\007\372B\004*\002 \000\022\035\n" +
      "\025allow_partial_message\030\002 \001(\010\022\025\n\rpack_as_" +
      "bytes\030\003 \001(\010:;\232\305\210\0366\n4envoy.config.filter." +
      "http.ext_authz.v2.BufferSettings\"\353\002\n\013Htt" +
      "pService\0221\n\nserver_uri\030\001 \001(\0132\035.envoy.con" +
      "fig.core.v3.HttpUri\022\023\n\013path_prefix\030\002 \001(\t" +
      "\022_\n\025authorization_request\030\007 \001(\0132@.envoy." +
      "extensions.filters.http.ext_authz.v3.Aut" +
      "horizationRequest\022a\n\026authorization_respo" +
      "nse\030\010 \001(\0132A.envoy.extensions.filters.htt" +
      "p.ext_authz.v3.AuthorizationResponse:8\232\305" +
      "\210\0363\n1envoy.config.filter.http.ext_authz." +
      "v2.HttpServiceJ\004\010\003\020\004J\004\010\004\020\005J\004\010\005\020\006J\004\010\006\020\007\"\327" +
      "\001\n\024AuthorizationRequest\022A\n\017allowed_heade" +
      "rs\030\001 \001(\0132(.envoy.type.matcher.v3.ListStr" +
      "ingMatcher\0229\n\016headers_to_add\030\002 \003(\0132!.env" +
      "oy.config.core.v3.HeaderValue:A\232\305\210\036<\n:en" +
      "voy.config.filter.http.ext_authz.v2.Auth" +
      "orizationRequest\"\307\002\n\025AuthorizationRespon" +
      "se\022J\n\030allowed_upstream_headers\030\001 \001(\0132(.e" +
      "nvoy.type.matcher.v3.ListStringMatcher\022T" +
      "\n\"allowed_upstream_headers_to_append\030\003 \001" +
      "(\0132(.envoy.type.matcher.v3.ListStringMat" +
      "cher\022H\n\026allowed_client_headers\030\002 \001(\0132(.e" +
      "nvoy.type.matcher.v3.ListStringMatcher:B" +
      "\232\305\210\036=\n;envoy.config.filter.http.ext_auth" +
      "z.v2.AuthorizationResponse\"\336\001\n\020ExtAuthzP" +
      "erRoute\022\033\n\010disabled\030\001 \001(\010B\007\372B\004j\002\010\001H\000\022]\n\016" +
      "check_settings\030\002 \001(\01329.envoy.extensions." +
      "filters.http.ext_authz.v3.CheckSettingsB" +
      "\010\372B\005\212\001\002\020\001H\000:=\232\305\210\0368\n6envoy.config.filter." +
      "http.ext_authz.v2.ExtAuthzPerRouteB\017\n\010ov" +
      "erride\022\003\370B\001\"\233\002\n\rCheckSettings\022l\n\022context" +
      "_extensions\030\001 \003(\0132P.envoy.extensions.fil" +
      "ters.http.ext_authz.v3.CheckSettings.Con" +
      "textExtensionsEntry\022&\n\036disable_request_b" +
      "ody_buffering\030\002 \001(\010\0328\n\026ContextExtensions" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001::\232" +
      "\305\210\0365\n3envoy.config.filter.http.ext_authz" +
      ".v2.CheckSettingsBS\n8io.envoyproxy.envoy" +
      ".extensions.filters.http.ext_authz.v3B\rE" +
      "xtAuthzProtoP\001\272\200\310\321\006\002\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.envoy.config.core.v3.BaseProto.getDescriptor(),
          io.envoyproxy.envoy.config.core.v3.ConfigSourceProto.getDescriptor(),
          io.envoyproxy.envoy.config.core.v3.GrpcServiceProto.getDescriptor(),
          io.envoyproxy.envoy.config.core.v3.HttpUriProto.getDescriptor(),
          io.envoyproxy.envoy.type.matcher.v3.MetadataProto.getDescriptor(),
          io.envoyproxy.envoy.type.matcher.v3.StringProto.getDescriptor(),
          io.envoyproxy.envoy.type.v3.HttpStatusProto.getDescriptor(),
          envoy.annotations.Deprecation.getDescriptor(),
          udpa.annotations.Status.getDescriptor(),
          udpa.annotations.Versioning.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthz_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthz_descriptor,
        new java.lang.String[] { "GrpcService", "HttpService", "TransportApiVersion", "FailureModeAllow", "WithRequestBody", "ClearRouteCache", "StatusOnError", "MetadataContextNamespaces", "FilterEnabled", "FilterEnabledMetadata", "DenyAtDisable", "IncludePeerCertificate", "StatPrefix", "Services", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_BufferSettings_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_BufferSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_BufferSettings_descriptor,
        new java.lang.String[] { "MaxRequestBytes", "AllowPartialMessage", "PackAsBytes", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_HttpService_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_HttpService_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_HttpService_descriptor,
        new java.lang.String[] { "ServerUri", "PathPrefix", "AuthorizationRequest", "AuthorizationResponse", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationRequest_descriptor,
        new java.lang.String[] { "AllowedHeaders", "HeadersToAdd", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_AuthorizationResponse_descriptor,
        new java.lang.String[] { "AllowedUpstreamHeaders", "AllowedUpstreamHeadersToAppend", "AllowedClientHeaders", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthzPerRoute_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthzPerRoute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_ExtAuthzPerRoute_descriptor,
        new java.lang.String[] { "Disabled", "CheckSettings", "Override", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_descriptor,
        new java.lang.String[] { "ContextExtensions", "DisableRequestBodyBuffering", });
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_ContextExtensionsEntry_descriptor =
      internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_descriptor.getNestedTypes().get(0);
    internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_ContextExtensionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_filters_http_ext_authz_v3_CheckSettings_ContextExtensionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(udpa.annotations.Status.fileStatus);
    registry.add(udpa.annotations.Versioning.versioning);
    registry.add(io.envoyproxy.pgv.validate.Validate.required);
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.envoy.config.core.v3.BaseProto.getDescriptor();
    io.envoyproxy.envoy.config.core.v3.ConfigSourceProto.getDescriptor();
    io.envoyproxy.envoy.config.core.v3.GrpcServiceProto.getDescriptor();
    io.envoyproxy.envoy.config.core.v3.HttpUriProto.getDescriptor();
    io.envoyproxy.envoy.type.matcher.v3.MetadataProto.getDescriptor();
    io.envoyproxy.envoy.type.matcher.v3.StringProto.getDescriptor();
    io.envoyproxy.envoy.type.v3.HttpStatusProto.getDescriptor();
    envoy.annotations.Deprecation.getDescriptor();
    udpa.annotations.Status.getDescriptor();
    udpa.annotations.Versioning.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
