// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto

package io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3;

/**
 * <pre>
 * [#next-free-field: 7]
 * </pre>
 *
 * Protobuf type {@code envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit}
 */
public final class LocalRateLimit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)
    LocalRateLimitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocalRateLimit.newBuilder() to construct.
  private LocalRateLimit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocalRateLimit() {
    statPrefix_ = "";
    responseHeadersToAdd_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocalRateLimit();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocalRateLimit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            statPrefix_ = s;
            break;
          }
          case 18: {
            io.envoyproxy.envoy.type.v3.HttpStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(io.envoyproxy.envoy.type.v3.HttpStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            io.envoyproxy.envoy.type.v3.TokenBucket.Builder subBuilder = null;
            if (tokenBucket_ != null) {
              subBuilder = tokenBucket_.toBuilder();
            }
            tokenBucket_ = input.readMessage(io.envoyproxy.envoy.type.v3.TokenBucket.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tokenBucket_);
              tokenBucket_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder subBuilder = null;
            if (filterEnabled_ != null) {
              subBuilder = filterEnabled_.toBuilder();
            }
            filterEnabled_ = input.readMessage(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filterEnabled_);
              filterEnabled_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder subBuilder = null;
            if (filterEnforced_ != null) {
              subBuilder = filterEnforced_.toBuilder();
            }
            filterEnforced_ = input.readMessage(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(filterEnforced_);
              filterEnforced_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              responseHeadersToAdd_ = new java.util.ArrayList<io.envoyproxy.envoy.config.core.v3.HeaderValueOption>();
              mutable_bitField0_ |= 0x00000001;
            }
            responseHeadersToAdd_.add(
                input.readMessage(io.envoyproxy.envoy.config.core.v3.HeaderValueOption.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        responseHeadersToAdd_ = java.util.Collections.unmodifiableList(responseHeadersToAdd_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitProto.internal_static_envoy_extensions_filters_http_local_ratelimit_v3_LocalRateLimit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitProto.internal_static_envoy_extensions_filters_http_local_ratelimit_v3_LocalRateLimit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.class, io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.Builder.class);
  }

  public static final int STAT_PREFIX_FIELD_NUMBER = 1;
  private volatile java.lang.Object statPrefix_;
  /**
   * <pre>
   * The human readable prefix to use when emitting stats.
   * </pre>
   *
   * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
   * @return The statPrefix.
   */
  @java.lang.Override
  public java.lang.String getStatPrefix() {
    java.lang.Object ref = statPrefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      statPrefix_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The human readable prefix to use when emitting stats.
   * </pre>
   *
   * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for statPrefix.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatPrefixBytes() {
    java.lang.Object ref = statPrefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      statPrefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private io.envoyproxy.envoy.type.v3.HttpStatus status_;
  /**
   * <pre>
   * This field allows for a custom HTTP response status code to the downstream client when
   * the request has been rate limited.
   * Defaults to 429 (TooManyRequests).
   * .. note::
   *   If this is set to &lt; 400, 429 will be used instead.
   * </pre>
   *
   * <code>.envoy.type.v3.HttpStatus status = 2;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * This field allows for a custom HTTP response status code to the downstream client when
   * the request has been rate limited.
   * Defaults to 429 (TooManyRequests).
   * .. note::
   *   If this is set to &lt; 400, 429 will be used instead.
   * </pre>
   *
   * <code>.envoy.type.v3.HttpStatus status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public io.envoyproxy.envoy.type.v3.HttpStatus getStatus() {
    return status_ == null ? io.envoyproxy.envoy.type.v3.HttpStatus.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * This field allows for a custom HTTP response status code to the downstream client when
   * the request has been rate limited.
   * Defaults to 429 (TooManyRequests).
   * .. note::
   *   If this is set to &lt; 400, 429 will be used instead.
   * </pre>
   *
   * <code>.envoy.type.v3.HttpStatus status = 2;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.type.v3.HttpStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int TOKEN_BUCKET_FIELD_NUMBER = 3;
  private io.envoyproxy.envoy.type.v3.TokenBucket tokenBucket_;
  /**
   * <pre>
   * The token bucket configuration to use for rate limiting requests that are processed by this
   * filter. Each request processed by the filter consumes a single token. If the token is available,
   * the request will be allowed. If no tokens are available, the request will receive the configured
   * rate limit status.
   * .. note::
   *   It's fine for the token bucket to be unset for the global configuration since the rate limit
   *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
   *   for the per route configuration otherwise the config will be rejected.
   * .. note::
   *   When using per route configuration, the bucket becomes unique to that route.
   * .. note::
   *   In the current implementation the token bucket's :ref:`fill_interval
   *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
   *   refills.
   * </pre>
   *
   * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
   * @return Whether the tokenBucket field is set.
   */
  @java.lang.Override
  public boolean hasTokenBucket() {
    return tokenBucket_ != null;
  }
  /**
   * <pre>
   * The token bucket configuration to use for rate limiting requests that are processed by this
   * filter. Each request processed by the filter consumes a single token. If the token is available,
   * the request will be allowed. If no tokens are available, the request will receive the configured
   * rate limit status.
   * .. note::
   *   It's fine for the token bucket to be unset for the global configuration since the rate limit
   *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
   *   for the per route configuration otherwise the config will be rejected.
   * .. note::
   *   When using per route configuration, the bucket becomes unique to that route.
   * .. note::
   *   In the current implementation the token bucket's :ref:`fill_interval
   *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
   *   refills.
   * </pre>
   *
   * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
   * @return The tokenBucket.
   */
  @java.lang.Override
  public io.envoyproxy.envoy.type.v3.TokenBucket getTokenBucket() {
    return tokenBucket_ == null ? io.envoyproxy.envoy.type.v3.TokenBucket.getDefaultInstance() : tokenBucket_;
  }
  /**
   * <pre>
   * The token bucket configuration to use for rate limiting requests that are processed by this
   * filter. Each request processed by the filter consumes a single token. If the token is available,
   * the request will be allowed. If no tokens are available, the request will receive the configured
   * rate limit status.
   * .. note::
   *   It's fine for the token bucket to be unset for the global configuration since the rate limit
   *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
   *   for the per route configuration otherwise the config will be rejected.
   * .. note::
   *   When using per route configuration, the bucket becomes unique to that route.
   * .. note::
   *   In the current implementation the token bucket's :ref:`fill_interval
   *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
   *   refills.
   * </pre>
   *
   * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.type.v3.TokenBucketOrBuilder getTokenBucketOrBuilder() {
    return getTokenBucket();
  }

  public static final int FILTER_ENABLED_FIELD_NUMBER = 4;
  private io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent filterEnabled_;
  /**
   * <pre>
   * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
   * fraction of requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
   * @return Whether the filterEnabled field is set.
   */
  @java.lang.Override
  public boolean hasFilterEnabled() {
    return filterEnabled_ != null;
  }
  /**
   * <pre>
   * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
   * fraction of requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
   * @return The filterEnabled.
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent getFilterEnabled() {
    return filterEnabled_ == null ? io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnabled_;
  }
  /**
   * <pre>
   * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
   * fraction of requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder getFilterEnabledOrBuilder() {
    return getFilterEnabled();
  }

  public static final int FILTER_ENFORCED_FIELD_NUMBER = 5;
  private io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent filterEnforced_;
  /**
   * <pre>
   * If set, this will enforce the rate limit decisions for the given fraction of requests.
   * Note: this only applies to the fraction of enabled requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
   * @return Whether the filterEnforced field is set.
   */
  @java.lang.Override
  public boolean hasFilterEnforced() {
    return filterEnforced_ != null;
  }
  /**
   * <pre>
   * If set, this will enforce the rate limit decisions for the given fraction of requests.
   * Note: this only applies to the fraction of enabled requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
   * @return The filterEnforced.
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent getFilterEnforced() {
    return filterEnforced_ == null ? io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnforced_;
  }
  /**
   * <pre>
   * If set, this will enforce the rate limit decisions for the given fraction of requests.
   * Note: this only applies to the fraction of enabled requests.
   * Defaults to 0% of requests for safety.
   * </pre>
   *
   * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder getFilterEnforcedOrBuilder() {
    return getFilterEnforced();
  }

  public static final int RESPONSE_HEADERS_TO_ADD_FIELD_NUMBER = 6;
  private java.util.List<io.envoyproxy.envoy.config.core.v3.HeaderValueOption> responseHeadersToAdd_;
  /**
   * <pre>
   * Specifies a list of HTTP headers that should be added to each response for requests that
   * have been rate limited.
   * </pre>
   *
   * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<io.envoyproxy.envoy.config.core.v3.HeaderValueOption> getResponseHeadersToAddList() {
    return responseHeadersToAdd_;
  }
  /**
   * <pre>
   * Specifies a list of HTTP headers that should be added to each response for requests that
   * have been rate limited.
   * </pre>
   *
   * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder> 
      getResponseHeadersToAddOrBuilderList() {
    return responseHeadersToAdd_;
  }
  /**
   * <pre>
   * Specifies a list of HTTP headers that should be added to each response for requests that
   * have been rate limited.
   * </pre>
   *
   * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public int getResponseHeadersToAddCount() {
    return responseHeadersToAdd_.size();
  }
  /**
   * <pre>
   * Specifies a list of HTTP headers that should be added to each response for requests that
   * have been rate limited.
   * </pre>
   *
   * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.HeaderValueOption getResponseHeadersToAdd(int index) {
    return responseHeadersToAdd_.get(index);
  }
  /**
   * <pre>
   * Specifies a list of HTTP headers that should be added to each response for requests that
   * have been rate limited.
   * </pre>
   *
   * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder getResponseHeadersToAddOrBuilder(
      int index) {
    return responseHeadersToAdd_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStatPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statPrefix_);
    }
    if (status_ != null) {
      output.writeMessage(2, getStatus());
    }
    if (tokenBucket_ != null) {
      output.writeMessage(3, getTokenBucket());
    }
    if (filterEnabled_ != null) {
      output.writeMessage(4, getFilterEnabled());
    }
    if (filterEnforced_ != null) {
      output.writeMessage(5, getFilterEnforced());
    }
    for (int i = 0; i < responseHeadersToAdd_.size(); i++) {
      output.writeMessage(6, responseHeadersToAdd_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStatPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statPrefix_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStatus());
    }
    if (tokenBucket_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTokenBucket());
    }
    if (filterEnabled_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFilterEnabled());
    }
    if (filterEnforced_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFilterEnforced());
    }
    for (int i = 0; i < responseHeadersToAdd_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, responseHeadersToAdd_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)) {
      return super.equals(obj);
    }
    io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit other = (io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit) obj;

    if (!getStatPrefix()
        .equals(other.getStatPrefix())) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasTokenBucket() != other.hasTokenBucket()) return false;
    if (hasTokenBucket()) {
      if (!getTokenBucket()
          .equals(other.getTokenBucket())) return false;
    }
    if (hasFilterEnabled() != other.hasFilterEnabled()) return false;
    if (hasFilterEnabled()) {
      if (!getFilterEnabled()
          .equals(other.getFilterEnabled())) return false;
    }
    if (hasFilterEnforced() != other.hasFilterEnforced()) return false;
    if (hasFilterEnforced()) {
      if (!getFilterEnforced()
          .equals(other.getFilterEnforced())) return false;
    }
    if (!getResponseHeadersToAddList()
        .equals(other.getResponseHeadersToAddList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STAT_PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getStatPrefix().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasTokenBucket()) {
      hash = (37 * hash) + TOKEN_BUCKET_FIELD_NUMBER;
      hash = (53 * hash) + getTokenBucket().hashCode();
    }
    if (hasFilterEnabled()) {
      hash = (37 * hash) + FILTER_ENABLED_FIELD_NUMBER;
      hash = (53 * hash) + getFilterEnabled().hashCode();
    }
    if (hasFilterEnforced()) {
      hash = (37 * hash) + FILTER_ENFORCED_FIELD_NUMBER;
      hash = (53 * hash) + getFilterEnforced().hashCode();
    }
    if (getResponseHeadersToAddCount() > 0) {
      hash = (37 * hash) + RESPONSE_HEADERS_TO_ADD_FIELD_NUMBER;
      hash = (53 * hash) + getResponseHeadersToAddList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * [#next-free-field: 7]
   * </pre>
   *
   * Protobuf type {@code envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)
      io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitProto.internal_static_envoy_extensions_filters_http_local_ratelimit_v3_LocalRateLimit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitProto.internal_static_envoy_extensions_filters_http_local_ratelimit_v3_LocalRateLimit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.class, io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.Builder.class);
    }

    // Construct using io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResponseHeadersToAddFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      statPrefix_ = "";

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (tokenBucketBuilder_ == null) {
        tokenBucket_ = null;
      } else {
        tokenBucket_ = null;
        tokenBucketBuilder_ = null;
      }
      if (filterEnabledBuilder_ == null) {
        filterEnabled_ = null;
      } else {
        filterEnabled_ = null;
        filterEnabledBuilder_ = null;
      }
      if (filterEnforcedBuilder_ == null) {
        filterEnforced_ = null;
      } else {
        filterEnforced_ = null;
        filterEnforcedBuilder_ = null;
      }
      if (responseHeadersToAddBuilder_ == null) {
        responseHeadersToAdd_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        responseHeadersToAddBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimitProto.internal_static_envoy_extensions_filters_http_local_ratelimit_v3_LocalRateLimit_descriptor;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit getDefaultInstanceForType() {
      return io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.getDefaultInstance();
    }

    @java.lang.Override
    public io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit build() {
      io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit buildPartial() {
      io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit result = new io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit(this);
      int from_bitField0_ = bitField0_;
      result.statPrefix_ = statPrefix_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (tokenBucketBuilder_ == null) {
        result.tokenBucket_ = tokenBucket_;
      } else {
        result.tokenBucket_ = tokenBucketBuilder_.build();
      }
      if (filterEnabledBuilder_ == null) {
        result.filterEnabled_ = filterEnabled_;
      } else {
        result.filterEnabled_ = filterEnabledBuilder_.build();
      }
      if (filterEnforcedBuilder_ == null) {
        result.filterEnforced_ = filterEnforced_;
      } else {
        result.filterEnforced_ = filterEnforcedBuilder_.build();
      }
      if (responseHeadersToAddBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          responseHeadersToAdd_ = java.util.Collections.unmodifiableList(responseHeadersToAdd_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.responseHeadersToAdd_ = responseHeadersToAdd_;
      } else {
        result.responseHeadersToAdd_ = responseHeadersToAddBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit) {
        return mergeFrom((io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit other) {
      if (other == io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit.getDefaultInstance()) return this;
      if (!other.getStatPrefix().isEmpty()) {
        statPrefix_ = other.statPrefix_;
        onChanged();
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasTokenBucket()) {
        mergeTokenBucket(other.getTokenBucket());
      }
      if (other.hasFilterEnabled()) {
        mergeFilterEnabled(other.getFilterEnabled());
      }
      if (other.hasFilterEnforced()) {
        mergeFilterEnforced(other.getFilterEnforced());
      }
      if (responseHeadersToAddBuilder_ == null) {
        if (!other.responseHeadersToAdd_.isEmpty()) {
          if (responseHeadersToAdd_.isEmpty()) {
            responseHeadersToAdd_ = other.responseHeadersToAdd_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResponseHeadersToAddIsMutable();
            responseHeadersToAdd_.addAll(other.responseHeadersToAdd_);
          }
          onChanged();
        }
      } else {
        if (!other.responseHeadersToAdd_.isEmpty()) {
          if (responseHeadersToAddBuilder_.isEmpty()) {
            responseHeadersToAddBuilder_.dispose();
            responseHeadersToAddBuilder_ = null;
            responseHeadersToAdd_ = other.responseHeadersToAdd_;
            bitField0_ = (bitField0_ & ~0x00000001);
            responseHeadersToAddBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResponseHeadersToAddFieldBuilder() : null;
          } else {
            responseHeadersToAddBuilder_.addAllMessages(other.responseHeadersToAdd_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object statPrefix_ = "";
    /**
     * <pre>
     * The human readable prefix to use when emitting stats.
     * </pre>
     *
     * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
     * @return The statPrefix.
     */
    public java.lang.String getStatPrefix() {
      java.lang.Object ref = statPrefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statPrefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The human readable prefix to use when emitting stats.
     * </pre>
     *
     * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for statPrefix.
     */
    public com.google.protobuf.ByteString
        getStatPrefixBytes() {
      java.lang.Object ref = statPrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The human readable prefix to use when emitting stats.
     * </pre>
     *
     * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
     * @param value The statPrefix to set.
     * @return This builder for chaining.
     */
    public Builder setStatPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      statPrefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human readable prefix to use when emitting stats.
     * </pre>
     *
     * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearStatPrefix() {
      
      statPrefix_ = getDefaultInstance().getStatPrefix();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human readable prefix to use when emitting stats.
     * </pre>
     *
     * <code>string stat_prefix = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for statPrefix to set.
     * @return This builder for chaining.
     */
    public Builder setStatPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      statPrefix_ = value;
      onChanged();
      return this;
    }

    private io.envoyproxy.envoy.type.v3.HttpStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.type.v3.HttpStatus, io.envoyproxy.envoy.type.v3.HttpStatus.Builder, io.envoyproxy.envoy.type.v3.HttpStatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     * @return The status.
     */
    public io.envoyproxy.envoy.type.v3.HttpStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? io.envoyproxy.envoy.type.v3.HttpStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public Builder setStatus(io.envoyproxy.envoy.type.v3.HttpStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public Builder setStatus(
        io.envoyproxy.envoy.type.v3.HttpStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public Builder mergeStatus(io.envoyproxy.envoy.type.v3.HttpStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            io.envoyproxy.envoy.type.v3.HttpStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public io.envoyproxy.envoy.type.v3.HttpStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    public io.envoyproxy.envoy.type.v3.HttpStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            io.envoyproxy.envoy.type.v3.HttpStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * This field allows for a custom HTTP response status code to the downstream client when
     * the request has been rate limited.
     * Defaults to 429 (TooManyRequests).
     * .. note::
     *   If this is set to &lt; 400, 429 will be used instead.
     * </pre>
     *
     * <code>.envoy.type.v3.HttpStatus status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.type.v3.HttpStatus, io.envoyproxy.envoy.type.v3.HttpStatus.Builder, io.envoyproxy.envoy.type.v3.HttpStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.envoyproxy.envoy.type.v3.HttpStatus, io.envoyproxy.envoy.type.v3.HttpStatus.Builder, io.envoyproxy.envoy.type.v3.HttpStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private io.envoyproxy.envoy.type.v3.TokenBucket tokenBucket_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.type.v3.TokenBucket, io.envoyproxy.envoy.type.v3.TokenBucket.Builder, io.envoyproxy.envoy.type.v3.TokenBucketOrBuilder> tokenBucketBuilder_;
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     * @return Whether the tokenBucket field is set.
     */
    public boolean hasTokenBucket() {
      return tokenBucketBuilder_ != null || tokenBucket_ != null;
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     * @return The tokenBucket.
     */
    public io.envoyproxy.envoy.type.v3.TokenBucket getTokenBucket() {
      if (tokenBucketBuilder_ == null) {
        return tokenBucket_ == null ? io.envoyproxy.envoy.type.v3.TokenBucket.getDefaultInstance() : tokenBucket_;
      } else {
        return tokenBucketBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public Builder setTokenBucket(io.envoyproxy.envoy.type.v3.TokenBucket value) {
      if (tokenBucketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tokenBucket_ = value;
        onChanged();
      } else {
        tokenBucketBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public Builder setTokenBucket(
        io.envoyproxy.envoy.type.v3.TokenBucket.Builder builderForValue) {
      if (tokenBucketBuilder_ == null) {
        tokenBucket_ = builderForValue.build();
        onChanged();
      } else {
        tokenBucketBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public Builder mergeTokenBucket(io.envoyproxy.envoy.type.v3.TokenBucket value) {
      if (tokenBucketBuilder_ == null) {
        if (tokenBucket_ != null) {
          tokenBucket_ =
            io.envoyproxy.envoy.type.v3.TokenBucket.newBuilder(tokenBucket_).mergeFrom(value).buildPartial();
        } else {
          tokenBucket_ = value;
        }
        onChanged();
      } else {
        tokenBucketBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public Builder clearTokenBucket() {
      if (tokenBucketBuilder_ == null) {
        tokenBucket_ = null;
        onChanged();
      } else {
        tokenBucket_ = null;
        tokenBucketBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public io.envoyproxy.envoy.type.v3.TokenBucket.Builder getTokenBucketBuilder() {
      
      onChanged();
      return getTokenBucketFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    public io.envoyproxy.envoy.type.v3.TokenBucketOrBuilder getTokenBucketOrBuilder() {
      if (tokenBucketBuilder_ != null) {
        return tokenBucketBuilder_.getMessageOrBuilder();
      } else {
        return tokenBucket_ == null ?
            io.envoyproxy.envoy.type.v3.TokenBucket.getDefaultInstance() : tokenBucket_;
      }
    }
    /**
     * <pre>
     * The token bucket configuration to use for rate limiting requests that are processed by this
     * filter. Each request processed by the filter consumes a single token. If the token is available,
     * the request will be allowed. If no tokens are available, the request will receive the configured
     * rate limit status.
     * .. note::
     *   It's fine for the token bucket to be unset for the global configuration since the rate limit
     *   can be applied at a the virtual host or route level. Thus, the token bucket must be set
     *   for the per route configuration otherwise the config will be rejected.
     * .. note::
     *   When using per route configuration, the bucket becomes unique to that route.
     * .. note::
     *   In the current implementation the token bucket's :ref:`fill_interval
     *   &lt;envoy_api_field_type.v3.TokenBucket.fill_interval&gt;` must be &gt;= 50ms to avoid too aggressive
     *   refills.
     * </pre>
     *
     * <code>.envoy.type.v3.TokenBucket token_bucket = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.type.v3.TokenBucket, io.envoyproxy.envoy.type.v3.TokenBucket.Builder, io.envoyproxy.envoy.type.v3.TokenBucketOrBuilder> 
        getTokenBucketFieldBuilder() {
      if (tokenBucketBuilder_ == null) {
        tokenBucketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.envoyproxy.envoy.type.v3.TokenBucket, io.envoyproxy.envoy.type.v3.TokenBucket.Builder, io.envoyproxy.envoy.type.v3.TokenBucketOrBuilder>(
                getTokenBucket(),
                getParentForChildren(),
                isClean());
        tokenBucket_ = null;
      }
      return tokenBucketBuilder_;
    }

    private io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent filterEnabled_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder> filterEnabledBuilder_;
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     * @return Whether the filterEnabled field is set.
     */
    public boolean hasFilterEnabled() {
      return filterEnabledBuilder_ != null || filterEnabled_ != null;
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     * @return The filterEnabled.
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent getFilterEnabled() {
      if (filterEnabledBuilder_ == null) {
        return filterEnabled_ == null ? io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnabled_;
      } else {
        return filterEnabledBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public Builder setFilterEnabled(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent value) {
      if (filterEnabledBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filterEnabled_ = value;
        onChanged();
      } else {
        filterEnabledBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public Builder setFilterEnabled(
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder builderForValue) {
      if (filterEnabledBuilder_ == null) {
        filterEnabled_ = builderForValue.build();
        onChanged();
      } else {
        filterEnabledBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public Builder mergeFilterEnabled(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent value) {
      if (filterEnabledBuilder_ == null) {
        if (filterEnabled_ != null) {
          filterEnabled_ =
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.newBuilder(filterEnabled_).mergeFrom(value).buildPartial();
        } else {
          filterEnabled_ = value;
        }
        onChanged();
      } else {
        filterEnabledBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public Builder clearFilterEnabled() {
      if (filterEnabledBuilder_ == null) {
        filterEnabled_ = null;
        onChanged();
      } else {
        filterEnabled_ = null;
        filterEnabledBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder getFilterEnabledBuilder() {
      
      onChanged();
      return getFilterEnabledFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder getFilterEnabledOrBuilder() {
      if (filterEnabledBuilder_ != null) {
        return filterEnabledBuilder_.getMessageOrBuilder();
      } else {
        return filterEnabled_ == null ?
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnabled_;
      }
    }
    /**
     * <pre>
     * If set, this will enable -- but not necessarily enforce -- the rate limit for the given
     * fraction of requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enabled = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder> 
        getFilterEnabledFieldBuilder() {
      if (filterEnabledBuilder_ == null) {
        filterEnabledBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder>(
                getFilterEnabled(),
                getParentForChildren(),
                isClean());
        filterEnabled_ = null;
      }
      return filterEnabledBuilder_;
    }

    private io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent filterEnforced_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder> filterEnforcedBuilder_;
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     * @return Whether the filterEnforced field is set.
     */
    public boolean hasFilterEnforced() {
      return filterEnforcedBuilder_ != null || filterEnforced_ != null;
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     * @return The filterEnforced.
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent getFilterEnforced() {
      if (filterEnforcedBuilder_ == null) {
        return filterEnforced_ == null ? io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnforced_;
      } else {
        return filterEnforcedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public Builder setFilterEnforced(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent value) {
      if (filterEnforcedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filterEnforced_ = value;
        onChanged();
      } else {
        filterEnforcedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public Builder setFilterEnforced(
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder builderForValue) {
      if (filterEnforcedBuilder_ == null) {
        filterEnforced_ = builderForValue.build();
        onChanged();
      } else {
        filterEnforcedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public Builder mergeFilterEnforced(io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent value) {
      if (filterEnforcedBuilder_ == null) {
        if (filterEnforced_ != null) {
          filterEnforced_ =
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.newBuilder(filterEnforced_).mergeFrom(value).buildPartial();
        } else {
          filterEnforced_ = value;
        }
        onChanged();
      } else {
        filterEnforcedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public Builder clearFilterEnforced() {
      if (filterEnforcedBuilder_ == null) {
        filterEnforced_ = null;
        onChanged();
      } else {
        filterEnforced_ = null;
        filterEnforcedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder getFilterEnforcedBuilder() {
      
      onChanged();
      return getFilterEnforcedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    public io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder getFilterEnforcedOrBuilder() {
      if (filterEnforcedBuilder_ != null) {
        return filterEnforcedBuilder_.getMessageOrBuilder();
      } else {
        return filterEnforced_ == null ?
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.getDefaultInstance() : filterEnforced_;
      }
    }
    /**
     * <pre>
     * If set, this will enforce the rate limit decisions for the given fraction of requests.
     * Note: this only applies to the fraction of enabled requests.
     * Defaults to 0% of requests for safety.
     * </pre>
     *
     * <code>.envoy.config.core.v3.RuntimeFractionalPercent filter_enforced = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder> 
        getFilterEnforcedFieldBuilder() {
      if (filterEnforcedBuilder_ == null) {
        filterEnforcedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercent.Builder, io.envoyproxy.envoy.config.core.v3.RuntimeFractionalPercentOrBuilder>(
                getFilterEnforced(),
                getParentForChildren(),
                isClean());
        filterEnforced_ = null;
      }
      return filterEnforcedBuilder_;
    }

    private java.util.List<io.envoyproxy.envoy.config.core.v3.HeaderValueOption> responseHeadersToAdd_ =
      java.util.Collections.emptyList();
    private void ensureResponseHeadersToAddIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        responseHeadersToAdd_ = new java.util.ArrayList<io.envoyproxy.envoy.config.core.v3.HeaderValueOption>(responseHeadersToAdd_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.HeaderValueOption, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder, io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder> responseHeadersToAddBuilder_;

    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public java.util.List<io.envoyproxy.envoy.config.core.v3.HeaderValueOption> getResponseHeadersToAddList() {
      if (responseHeadersToAddBuilder_ == null) {
        return java.util.Collections.unmodifiableList(responseHeadersToAdd_);
      } else {
        return responseHeadersToAddBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public int getResponseHeadersToAddCount() {
      if (responseHeadersToAddBuilder_ == null) {
        return responseHeadersToAdd_.size();
      } else {
        return responseHeadersToAddBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public io.envoyproxy.envoy.config.core.v3.HeaderValueOption getResponseHeadersToAdd(int index) {
      if (responseHeadersToAddBuilder_ == null) {
        return responseHeadersToAdd_.get(index);
      } else {
        return responseHeadersToAddBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder setResponseHeadersToAdd(
        int index, io.envoyproxy.envoy.config.core.v3.HeaderValueOption value) {
      if (responseHeadersToAddBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.set(index, value);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder setResponseHeadersToAdd(
        int index, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder builderForValue) {
      if (responseHeadersToAddBuilder_ == null) {
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.set(index, builderForValue.build());
        onChanged();
      } else {
        responseHeadersToAddBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder addResponseHeadersToAdd(io.envoyproxy.envoy.config.core.v3.HeaderValueOption value) {
      if (responseHeadersToAddBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.add(value);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder addResponseHeadersToAdd(
        int index, io.envoyproxy.envoy.config.core.v3.HeaderValueOption value) {
      if (responseHeadersToAddBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.add(index, value);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder addResponseHeadersToAdd(
        io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder builderForValue) {
      if (responseHeadersToAddBuilder_ == null) {
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.add(builderForValue.build());
        onChanged();
      } else {
        responseHeadersToAddBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder addResponseHeadersToAdd(
        int index, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder builderForValue) {
      if (responseHeadersToAddBuilder_ == null) {
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.add(index, builderForValue.build());
        onChanged();
      } else {
        responseHeadersToAddBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder addAllResponseHeadersToAdd(
        java.lang.Iterable<? extends io.envoyproxy.envoy.config.core.v3.HeaderValueOption> values) {
      if (responseHeadersToAddBuilder_ == null) {
        ensureResponseHeadersToAddIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, responseHeadersToAdd_);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder clearResponseHeadersToAdd() {
      if (responseHeadersToAddBuilder_ == null) {
        responseHeadersToAdd_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public Builder removeResponseHeadersToAdd(int index) {
      if (responseHeadersToAddBuilder_ == null) {
        ensureResponseHeadersToAddIsMutable();
        responseHeadersToAdd_.remove(index);
        onChanged();
      } else {
        responseHeadersToAddBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder getResponseHeadersToAddBuilder(
        int index) {
      return getResponseHeadersToAddFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder getResponseHeadersToAddOrBuilder(
        int index) {
      if (responseHeadersToAddBuilder_ == null) {
        return responseHeadersToAdd_.get(index);  } else {
        return responseHeadersToAddBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public java.util.List<? extends io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder> 
         getResponseHeadersToAddOrBuilderList() {
      if (responseHeadersToAddBuilder_ != null) {
        return responseHeadersToAddBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(responseHeadersToAdd_);
      }
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder addResponseHeadersToAddBuilder() {
      return getResponseHeadersToAddFieldBuilder().addBuilder(
          io.envoyproxy.envoy.config.core.v3.HeaderValueOption.getDefaultInstance());
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder addResponseHeadersToAddBuilder(
        int index) {
      return getResponseHeadersToAddFieldBuilder().addBuilder(
          index, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.getDefaultInstance());
    }
    /**
     * <pre>
     * Specifies a list of HTTP headers that should be added to each response for requests that
     * have been rate limited.
     * </pre>
     *
     * <code>repeated .envoy.config.core.v3.HeaderValueOption response_headers_to_add = 6 [(.validate.rules) = { ... }</code>
     */
    public java.util.List<io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder> 
         getResponseHeadersToAddBuilderList() {
      return getResponseHeadersToAddFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.envoyproxy.envoy.config.core.v3.HeaderValueOption, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder, io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder> 
        getResponseHeadersToAddFieldBuilder() {
      if (responseHeadersToAddBuilder_ == null) {
        responseHeadersToAddBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.envoyproxy.envoy.config.core.v3.HeaderValueOption, io.envoyproxy.envoy.config.core.v3.HeaderValueOption.Builder, io.envoyproxy.envoy.config.core.v3.HeaderValueOptionOrBuilder>(
                responseHeadersToAdd_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        responseHeadersToAdd_ = null;
      }
      return responseHeadersToAddBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)
  }

  // @@protoc_insertion_point(class_scope:envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit)
  private static final io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit();
  }

  public static io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocalRateLimit>
      PARSER = new com.google.protobuf.AbstractParser<LocalRateLimit>() {
    @java.lang.Override
    public LocalRateLimit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocalRateLimit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocalRateLimit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocalRateLimit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.envoyproxy.envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

