// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/config/tap/v3/common.proto

package io.envoyproxy.envoy.config.tap.v3;

public interface FilePerTapSinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:envoy.config.tap.v3.FilePerTapSink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Path prefix. The output file will be of the form &lt;path_prefix&gt;_&lt;id&gt;.pb, where &lt;id&gt; is an
   * identifier distinguishing the recorded trace for stream instances (the Envoy
   * connection ID, HTTP stream ID, etc.).
   * </pre>
   *
   * <code>string path_prefix = 1 [(.validate.rules) = { ... }</code>
   * @return The pathPrefix.
   */
  java.lang.String getPathPrefix();
  /**
   * <pre>
   * Path prefix. The output file will be of the form &lt;path_prefix&gt;_&lt;id&gt;.pb, where &lt;id&gt; is an
   * identifier distinguishing the recorded trace for stream instances (the Envoy
   * connection ID, HTTP stream ID, etc.).
   * </pre>
   *
   * <code>string path_prefix = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for pathPrefix.
   */
  com.google.protobuf.ByteString
      getPathPrefixBytes();
}
