// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/service/status/v3/csds.proto

package io.envoyproxy.envoy.service.status.v3;

/**
 * Protobuf type {@code envoy.service.status.v3.ClientStatusResponse}
 */
public final class ClientStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:envoy.service.status.v3.ClientStatusResponse)
    ClientStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientStatusResponse.newBuilder() to construct.
  private ClientStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientStatusResponse() {
    config_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientStatusResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              config_ = new java.util.ArrayList<io.envoyproxy.envoy.service.status.v3.ClientConfig>();
              mutable_bitField0_ |= 0x00000001;
            }
            config_.add(
                input.readMessage(io.envoyproxy.envoy.service.status.v3.ClientConfig.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        config_ = java.util.Collections.unmodifiableList(config_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.envoyproxy.envoy.service.status.v3.CsdsProto.internal_static_envoy_service_status_v3_ClientStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.envoyproxy.envoy.service.status.v3.CsdsProto.internal_static_envoy_service_status_v3_ClientStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.class, io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.Builder.class);
  }

  public static final int CONFIG_FIELD_NUMBER = 1;
  private java.util.List<io.envoyproxy.envoy.service.status.v3.ClientConfig> config_;
  /**
   * <pre>
   * Client configs for the clients specified in the ClientStatusRequest.
   * </pre>
   *
   * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.envoyproxy.envoy.service.status.v3.ClientConfig> getConfigList() {
    return config_;
  }
  /**
   * <pre>
   * Client configs for the clients specified in the ClientStatusRequest.
   * </pre>
   *
   * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder> 
      getConfigOrBuilderList() {
    return config_;
  }
  /**
   * <pre>
   * Client configs for the clients specified in the ClientStatusRequest.
   * </pre>
   *
   * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
   */
  @java.lang.Override
  public int getConfigCount() {
    return config_.size();
  }
  /**
   * <pre>
   * Client configs for the clients specified in the ClientStatusRequest.
   * </pre>
   *
   * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.service.status.v3.ClientConfig getConfig(int index) {
    return config_.get(index);
  }
  /**
   * <pre>
   * Client configs for the clients specified in the ClientStatusRequest.
   * </pre>
   *
   * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
   */
  @java.lang.Override
  public io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder getConfigOrBuilder(
      int index) {
    return config_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < config_.size(); i++) {
      output.writeMessage(1, config_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < config_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, config_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.envoyproxy.envoy.service.status.v3.ClientStatusResponse)) {
      return super.equals(obj);
    }
    io.envoyproxy.envoy.service.status.v3.ClientStatusResponse other = (io.envoyproxy.envoy.service.status.v3.ClientStatusResponse) obj;

    if (!getConfigList()
        .equals(other.getConfigList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getConfigCount() > 0) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfigList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.envoyproxy.envoy.service.status.v3.ClientStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code envoy.service.status.v3.ClientStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:envoy.service.status.v3.ClientStatusResponse)
      io.envoyproxy.envoy.service.status.v3.ClientStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.envoyproxy.envoy.service.status.v3.CsdsProto.internal_static_envoy_service_status_v3_ClientStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.envoyproxy.envoy.service.status.v3.CsdsProto.internal_static_envoy_service_status_v3_ClientStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.class, io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.Builder.class);
    }

    // Construct using io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (configBuilder_ == null) {
        config_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        configBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.envoyproxy.envoy.service.status.v3.CsdsProto.internal_static_envoy_service_status_v3_ClientStatusResponse_descriptor;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.service.status.v3.ClientStatusResponse getDefaultInstanceForType() {
      return io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.envoyproxy.envoy.service.status.v3.ClientStatusResponse build() {
      io.envoyproxy.envoy.service.status.v3.ClientStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.service.status.v3.ClientStatusResponse buildPartial() {
      io.envoyproxy.envoy.service.status.v3.ClientStatusResponse result = new io.envoyproxy.envoy.service.status.v3.ClientStatusResponse(this);
      int from_bitField0_ = bitField0_;
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          config_ = java.util.Collections.unmodifiableList(config_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.config_ = config_;
      } else {
        result.config_ = configBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.envoyproxy.envoy.service.status.v3.ClientStatusResponse) {
        return mergeFrom((io.envoyproxy.envoy.service.status.v3.ClientStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.envoyproxy.envoy.service.status.v3.ClientStatusResponse other) {
      if (other == io.envoyproxy.envoy.service.status.v3.ClientStatusResponse.getDefaultInstance()) return this;
      if (configBuilder_ == null) {
        if (!other.config_.isEmpty()) {
          if (config_.isEmpty()) {
            config_ = other.config_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureConfigIsMutable();
            config_.addAll(other.config_);
          }
          onChanged();
        }
      } else {
        if (!other.config_.isEmpty()) {
          if (configBuilder_.isEmpty()) {
            configBuilder_.dispose();
            configBuilder_ = null;
            config_ = other.config_;
            bitField0_ = (bitField0_ & ~0x00000001);
            configBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigFieldBuilder() : null;
          } else {
            configBuilder_.addAllMessages(other.config_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.envoyproxy.envoy.service.status.v3.ClientStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.envoyproxy.envoy.service.status.v3.ClientStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.envoyproxy.envoy.service.status.v3.ClientConfig> config_ =
      java.util.Collections.emptyList();
    private void ensureConfigIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        config_ = new java.util.ArrayList<io.envoyproxy.envoy.service.status.v3.ClientConfig>(config_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.envoyproxy.envoy.service.status.v3.ClientConfig, io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder, io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder> configBuilder_;

    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public java.util.List<io.envoyproxy.envoy.service.status.v3.ClientConfig> getConfigList() {
      if (configBuilder_ == null) {
        return java.util.Collections.unmodifiableList(config_);
      } else {
        return configBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public int getConfigCount() {
      if (configBuilder_ == null) {
        return config_.size();
      } else {
        return configBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public io.envoyproxy.envoy.service.status.v3.ClientConfig getConfig(int index) {
      if (configBuilder_ == null) {
        return config_.get(index);
      } else {
        return configBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder setConfig(
        int index, io.envoyproxy.envoy.service.status.v3.ClientConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigIsMutable();
        config_.set(index, value);
        onChanged();
      } else {
        configBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder setConfig(
        int index, io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        ensureConfigIsMutable();
        config_.set(index, builderForValue.build());
        onChanged();
      } else {
        configBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder addConfig(io.envoyproxy.envoy.service.status.v3.ClientConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigIsMutable();
        config_.add(value);
        onChanged();
      } else {
        configBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder addConfig(
        int index, io.envoyproxy.envoy.service.status.v3.ClientConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigIsMutable();
        config_.add(index, value);
        onChanged();
      } else {
        configBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder addConfig(
        io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        ensureConfigIsMutable();
        config_.add(builderForValue.build());
        onChanged();
      } else {
        configBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder addConfig(
        int index, io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        ensureConfigIsMutable();
        config_.add(index, builderForValue.build());
        onChanged();
      } else {
        configBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder addAllConfig(
        java.lang.Iterable<? extends io.envoyproxy.envoy.service.status.v3.ClientConfig> values) {
      if (configBuilder_ == null) {
        ensureConfigIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, config_);
        onChanged();
      } else {
        configBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        config_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        configBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public Builder removeConfig(int index) {
      if (configBuilder_ == null) {
        ensureConfigIsMutable();
        config_.remove(index);
        onChanged();
      } else {
        configBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder getConfigBuilder(
        int index) {
      return getConfigFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder getConfigOrBuilder(
        int index) {
      if (configBuilder_ == null) {
        return config_.get(index);  } else {
        return configBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public java.util.List<? extends io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder> 
         getConfigOrBuilderList() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(config_);
      }
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder addConfigBuilder() {
      return getConfigFieldBuilder().addBuilder(
          io.envoyproxy.envoy.service.status.v3.ClientConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder addConfigBuilder(
        int index) {
      return getConfigFieldBuilder().addBuilder(
          index, io.envoyproxy.envoy.service.status.v3.ClientConfig.getDefaultInstance());
    }
    /**
     * <pre>
     * Client configs for the clients specified in the ClientStatusRequest.
     * </pre>
     *
     * <code>repeated .envoy.service.status.v3.ClientConfig config = 1;</code>
     */
    public java.util.List<io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder> 
         getConfigBuilderList() {
      return getConfigFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.envoyproxy.envoy.service.status.v3.ClientConfig, io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder, io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.envoyproxy.envoy.service.status.v3.ClientConfig, io.envoyproxy.envoy.service.status.v3.ClientConfig.Builder, io.envoyproxy.envoy.service.status.v3.ClientConfigOrBuilder>(
                config_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:envoy.service.status.v3.ClientStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:envoy.service.status.v3.ClientStatusResponse)
  private static final io.envoyproxy.envoy.service.status.v3.ClientStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.envoyproxy.envoy.service.status.v3.ClientStatusResponse();
  }

  public static io.envoyproxy.envoy.service.status.v3.ClientStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<ClientStatusResponse>() {
    @java.lang.Override
    public ClientStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.envoyproxy.envoy.service.status.v3.ClientStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

