// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/extensions/rate_limit_descriptors/expr/v3/expr.proto

package io.envoyproxy.envoy.extensions.rate_limit_descriptors.expr.v3;

public interface DescriptorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:envoy.extensions.rate_limit_descriptors.expr.v3.Descriptor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The key to use in the descriptor entry.
   * </pre>
   *
   * <code>string descriptor_key = 1 [(.validate.rules) = { ... }</code>
   * @return The descriptorKey.
   */
  java.lang.String getDescriptorKey();
  /**
   * <pre>
   * The key to use in the descriptor entry.
   * </pre>
   *
   * <code>string descriptor_key = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for descriptorKey.
   */
  com.google.protobuf.ByteString
      getDescriptorKeyBytes();

  /**
   * <pre>
   * If set to true, Envoy skips the descriptor if the expression evaluates to an error.
   * By default, the rate limit is not applied when an expression produces an error.
   * </pre>
   *
   * <code>bool skip_if_error = 2;</code>
   * @return The skipIfError.
   */
  boolean getSkipIfError();

  /**
   * <pre>
   * Expression in a text form, e.g. "connection.requested_server_name".
   * </pre>
   *
   * <code>string text = 3 [(.validate.rules) = { ... }</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <pre>
   * Expression in a text form, e.g. "connection.requested_server_name".
   * </pre>
   *
   * <code>string text = 3 [(.validate.rules) = { ... }</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * Expression in a text form, e.g. "connection.requested_server_name".
   * </pre>
   *
   * <code>string text = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * Parsed expression in AST form.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.Expr parsed = 4;</code>
   * @return Whether the parsed field is set.
   */
  boolean hasParsed();
  /**
   * <pre>
   * Parsed expression in AST form.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.Expr parsed = 4;</code>
   * @return The parsed.
   */
  com.google.api.expr.v1alpha1.Expr getParsed();
  /**
   * <pre>
   * Parsed expression in AST form.
   * </pre>
   *
   * <code>.google.api.expr.v1alpha1.Expr parsed = 4;</code>
   */
  com.google.api.expr.v1alpha1.ExprOrBuilder getParsedOrBuilder();

  public io.envoyproxy.envoy.extensions.rate_limit_descriptors.expr.v3.Descriptor.ExprSpecifierCase getExprSpecifierCase();
}
