// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/data/tap/v3/common.proto

package io.envoyproxy.envoy.data.tap.v3;

/**
 * <pre>
 * Wrapper for tapped body data. This includes HTTP request/response body, transport socket received
 * and transmitted data, etc.
 * </pre>
 *
 * Protobuf type {@code envoy.data.tap.v3.Body}
 */
public final class Body extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:envoy.data.tap.v3.Body)
    BodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Body.newBuilder() to construct.
  private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Body() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Body();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Body(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            bodyTypeCase_ = 1;
            bodyType_ = input.readBytes();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            bodyTypeCase_ = 2;
            bodyType_ = s;
            break;
          }
          case 24: {

            truncated_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.envoyproxy.envoy.data.tap.v3.CommonProto.internal_static_envoy_data_tap_v3_Body_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.envoyproxy.envoy.data.tap.v3.CommonProto.internal_static_envoy_data_tap_v3_Body_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.envoyproxy.envoy.data.tap.v3.Body.class, io.envoyproxy.envoy.data.tap.v3.Body.Builder.class);
  }

  private int bodyTypeCase_ = 0;
  private java.lang.Object bodyType_;
  public enum BodyTypeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    AS_BYTES(1),
    AS_STRING(2),
    BODYTYPE_NOT_SET(0);
    private final int value;
    private BodyTypeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyTypeCase forNumber(int value) {
      switch (value) {
        case 1: return AS_BYTES;
        case 2: return AS_STRING;
        case 0: return BODYTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyTypeCase
  getBodyTypeCase() {
    return BodyTypeCase.forNumber(
        bodyTypeCase_);
  }

  public static final int AS_BYTES_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Body data as bytes. By default, tap body data will be present in this field, as the proto
   * `bytes` type can contain any valid byte.
   * </pre>
   *
   * <code>bytes as_bytes = 1;</code>
   * @return Whether the asBytes field is set.
   */
  @java.lang.Override
  public boolean hasAsBytes() {
    return bodyTypeCase_ == 1;
  }
  /**
   * <pre>
   * Body data as bytes. By default, tap body data will be present in this field, as the proto
   * `bytes` type can contain any valid byte.
   * </pre>
   *
   * <code>bytes as_bytes = 1;</code>
   * @return The asBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAsBytes() {
    if (bodyTypeCase_ == 1) {
      return (com.google.protobuf.ByteString) bodyType_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int AS_STRING_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
   * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
   * format type is selected. See the documentation for that option for why this is useful.
   * </pre>
   *
   * <code>string as_string = 2;</code>
   * @return Whether the asString field is set.
   */
  public boolean hasAsString() {
    return bodyTypeCase_ == 2;
  }
  /**
   * <pre>
   * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
   * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
   * format type is selected. See the documentation for that option for why this is useful.
   * </pre>
   *
   * <code>string as_string = 2;</code>
   * @return The asString.
   */
  public java.lang.String getAsString() {
    java.lang.Object ref = "";
    if (bodyTypeCase_ == 2) {
      ref = bodyType_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyTypeCase_ == 2) {
        bodyType_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
   * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
   * format type is selected. See the documentation for that option for why this is useful.
   * </pre>
   *
   * <code>string as_string = 2;</code>
   * @return The bytes for asString.
   */
  public com.google.protobuf.ByteString
      getAsStringBytes() {
    java.lang.Object ref = "";
    if (bodyTypeCase_ == 2) {
      ref = bodyType_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyTypeCase_ == 2) {
        bodyType_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRUNCATED_FIELD_NUMBER = 3;
  private boolean truncated_;
  /**
   * <pre>
   * Specifies whether body data has been truncated to fit within the specified
   * :ref:`max_buffered_rx_bytes
   * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_rx_bytes&gt;` and
   * :ref:`max_buffered_tx_bytes
   * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_tx_bytes&gt;` settings.
   * </pre>
   *
   * <code>bool truncated = 3;</code>
   * @return The truncated.
   */
  @java.lang.Override
  public boolean getTruncated() {
    return truncated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bodyTypeCase_ == 1) {
      output.writeBytes(
          1, (com.google.protobuf.ByteString) bodyType_);
    }
    if (bodyTypeCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bodyType_);
    }
    if (truncated_ != false) {
      output.writeBool(3, truncated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bodyTypeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            1, (com.google.protobuf.ByteString) bodyType_);
    }
    if (bodyTypeCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bodyType_);
    }
    if (truncated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, truncated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.envoyproxy.envoy.data.tap.v3.Body)) {
      return super.equals(obj);
    }
    io.envoyproxy.envoy.data.tap.v3.Body other = (io.envoyproxy.envoy.data.tap.v3.Body) obj;

    if (getTruncated()
        != other.getTruncated()) return false;
    if (!getBodyTypeCase().equals(other.getBodyTypeCase())) return false;
    switch (bodyTypeCase_) {
      case 1:
        if (!getAsBytes()
            .equals(other.getAsBytes())) return false;
        break;
      case 2:
        if (!getAsString()
            .equals(other.getAsString())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRUNCATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTruncated());
    switch (bodyTypeCase_) {
      case 1:
        hash = (37 * hash) + AS_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getAsBytes().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AS_STRING_FIELD_NUMBER;
        hash = (53 * hash) + getAsString().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.envoy.data.tap.v3.Body parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.envoyproxy.envoy.data.tap.v3.Body prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wrapper for tapped body data. This includes HTTP request/response body, transport socket received
   * and transmitted data, etc.
   * </pre>
   *
   * Protobuf type {@code envoy.data.tap.v3.Body}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:envoy.data.tap.v3.Body)
      io.envoyproxy.envoy.data.tap.v3.BodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.envoyproxy.envoy.data.tap.v3.CommonProto.internal_static_envoy_data_tap_v3_Body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.envoyproxy.envoy.data.tap.v3.CommonProto.internal_static_envoy_data_tap_v3_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.envoyproxy.envoy.data.tap.v3.Body.class, io.envoyproxy.envoy.data.tap.v3.Body.Builder.class);
    }

    // Construct using io.envoyproxy.envoy.data.tap.v3.Body.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      truncated_ = false;

      bodyTypeCase_ = 0;
      bodyType_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.envoyproxy.envoy.data.tap.v3.CommonProto.internal_static_envoy_data_tap_v3_Body_descriptor;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.data.tap.v3.Body getDefaultInstanceForType() {
      return io.envoyproxy.envoy.data.tap.v3.Body.getDefaultInstance();
    }

    @java.lang.Override
    public io.envoyproxy.envoy.data.tap.v3.Body build() {
      io.envoyproxy.envoy.data.tap.v3.Body result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.envoyproxy.envoy.data.tap.v3.Body buildPartial() {
      io.envoyproxy.envoy.data.tap.v3.Body result = new io.envoyproxy.envoy.data.tap.v3.Body(this);
      if (bodyTypeCase_ == 1) {
        result.bodyType_ = bodyType_;
      }
      if (bodyTypeCase_ == 2) {
        result.bodyType_ = bodyType_;
      }
      result.truncated_ = truncated_;
      result.bodyTypeCase_ = bodyTypeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.envoyproxy.envoy.data.tap.v3.Body) {
        return mergeFrom((io.envoyproxy.envoy.data.tap.v3.Body)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.envoyproxy.envoy.data.tap.v3.Body other) {
      if (other == io.envoyproxy.envoy.data.tap.v3.Body.getDefaultInstance()) return this;
      if (other.getTruncated() != false) {
        setTruncated(other.getTruncated());
      }
      switch (other.getBodyTypeCase()) {
        case AS_BYTES: {
          setAsBytes(other.getAsBytes());
          break;
        }
        case AS_STRING: {
          bodyTypeCase_ = 2;
          bodyType_ = other.bodyType_;
          onChanged();
          break;
        }
        case BODYTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.envoyproxy.envoy.data.tap.v3.Body parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.envoyproxy.envoy.data.tap.v3.Body) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bodyTypeCase_ = 0;
    private java.lang.Object bodyType_;
    public BodyTypeCase
        getBodyTypeCase() {
      return BodyTypeCase.forNumber(
          bodyTypeCase_);
    }

    public Builder clearBodyType() {
      bodyTypeCase_ = 0;
      bodyType_ = null;
      onChanged();
      return this;
    }


    /**
     * <pre>
     * Body data as bytes. By default, tap body data will be present in this field, as the proto
     * `bytes` type can contain any valid byte.
     * </pre>
     *
     * <code>bytes as_bytes = 1;</code>
     * @return Whether the asBytes field is set.
     */
    public boolean hasAsBytes() {
      return bodyTypeCase_ == 1;
    }
    /**
     * <pre>
     * Body data as bytes. By default, tap body data will be present in this field, as the proto
     * `bytes` type can contain any valid byte.
     * </pre>
     *
     * <code>bytes as_bytes = 1;</code>
     * @return The asBytes.
     */
    public com.google.protobuf.ByteString getAsBytes() {
      if (bodyTypeCase_ == 1) {
        return (com.google.protobuf.ByteString) bodyType_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <pre>
     * Body data as bytes. By default, tap body data will be present in this field, as the proto
     * `bytes` type can contain any valid byte.
     * </pre>
     *
     * <code>bytes as_bytes = 1;</code>
     * @param value The asBytes to set.
     * @return This builder for chaining.
     */
    public Builder setAsBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyTypeCase_ = 1;
      bodyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body data as bytes. By default, tap body data will be present in this field, as the proto
     * `bytes` type can contain any valid byte.
     * </pre>
     *
     * <code>bytes as_bytes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsBytes() {
      if (bodyTypeCase_ == 1) {
        bodyTypeCase_ = 0;
        bodyType_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @return Whether the asString field is set.
     */
    @java.lang.Override
    public boolean hasAsString() {
      return bodyTypeCase_ == 2;
    }
    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @return The asString.
     */
    @java.lang.Override
    public java.lang.String getAsString() {
      java.lang.Object ref = "";
      if (bodyTypeCase_ == 2) {
        ref = bodyType_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyTypeCase_ == 2) {
          bodyType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @return The bytes for asString.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAsStringBytes() {
      java.lang.Object ref = "";
      if (bodyTypeCase_ == 2) {
        ref = bodyType_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyTypeCase_ == 2) {
          bodyType_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @param value The asString to set.
     * @return This builder for chaining.
     */
    public Builder setAsString(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyTypeCase_ = 2;
      bodyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsString() {
      if (bodyTypeCase_ == 2) {
        bodyTypeCase_ = 0;
        bodyType_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Body data as string. This field is only used when the :ref:`JSON_BODY_AS_STRING
     * &lt;envoy_api_enum_value_config.tap.v3.OutputSink.Format.JSON_BODY_AS_STRING&gt;` sink
     * format type is selected. See the documentation for that option for why this is useful.
     * </pre>
     *
     * <code>string as_string = 2;</code>
     * @param value The bytes for asString to set.
     * @return This builder for chaining.
     */
    public Builder setAsStringBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyTypeCase_ = 2;
      bodyType_ = value;
      onChanged();
      return this;
    }

    private boolean truncated_ ;
    /**
     * <pre>
     * Specifies whether body data has been truncated to fit within the specified
     * :ref:`max_buffered_rx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_rx_bytes&gt;` and
     * :ref:`max_buffered_tx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_tx_bytes&gt;` settings.
     * </pre>
     *
     * <code>bool truncated = 3;</code>
     * @return The truncated.
     */
    @java.lang.Override
    public boolean getTruncated() {
      return truncated_;
    }
    /**
     * <pre>
     * Specifies whether body data has been truncated to fit within the specified
     * :ref:`max_buffered_rx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_rx_bytes&gt;` and
     * :ref:`max_buffered_tx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_tx_bytes&gt;` settings.
     * </pre>
     *
     * <code>bool truncated = 3;</code>
     * @param value The truncated to set.
     * @return This builder for chaining.
     */
    public Builder setTruncated(boolean value) {
      
      truncated_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Specifies whether body data has been truncated to fit within the specified
     * :ref:`max_buffered_rx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_rx_bytes&gt;` and
     * :ref:`max_buffered_tx_bytes
     * &lt;envoy_api_field_config.tap.v3.OutputConfig.max_buffered_tx_bytes&gt;` settings.
     * </pre>
     *
     * <code>bool truncated = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTruncated() {
      
      truncated_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:envoy.data.tap.v3.Body)
  }

  // @@protoc_insertion_point(class_scope:envoy.data.tap.v3.Body)
  private static final io.envoyproxy.envoy.data.tap.v3.Body DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.envoyproxy.envoy.data.tap.v3.Body();
  }

  public static io.envoyproxy.envoy.data.tap.v3.Body getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Body>
      PARSER = new com.google.protobuf.AbstractParser<Body>() {
    @java.lang.Override
    public Body parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Body(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Body> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Body> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.envoyproxy.envoy.data.tap.v3.Body getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

