// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envoy/extensions/common/matching/v3/extension_matcher.proto

package io.envoyproxy.envoy.extensions.common.matching.v3;

public final class ExtensionMatcherProto {
  private ExtensionMatcherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_envoy_extensions_common_matching_v3_ExtensionWithMatcher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_envoy_extensions_common_matching_v3_ExtensionWithMatcher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;envoy/extensions/common/matching/v3/ex" +
      "tension_matcher.proto\022#envoy.extensions." +
      "common.matching.v3\032,envoy/config/common/" +
      "matcher/v3/matcher.proto\032$envoy/config/c" +
      "ore/v3/extension.proto\032\036udpa/annotations" +
      "/migrate.proto\032\035udpa/annotations/status." +
      "proto\032\027validate/validate.proto\"\252\001\n\024Exten" +
      "sionWithMatcher\022B\n\007matcher\030\001 \001(\0132\'.envoy" +
      ".config.common.matcher.v3.MatcherB\010\372B\005\212\001" +
      "\002\020\001\022N\n\020extension_config\030\002 \001(\0132*.envoy.co" +
      "nfig.core.v3.TypedExtensionConfigB\010\372B\005\212\001" +
      "\002\020\001BT\n1io.envoyproxy.envoy.extensions.co" +
      "mmon.matching.v3B\025ExtensionMatcherProtoP" +
      "\001\272\200\310\321\006\002\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.envoy.config.common.matcher.v3.MatcherProto.getDescriptor(),
          io.envoyproxy.envoy.config.core.v3.ExtensionProto.getDescriptor(),
          udpa.annotations.Migrate.getDescriptor(),
          udpa.annotations.Status.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_envoy_extensions_common_matching_v3_ExtensionWithMatcher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_envoy_extensions_common_matching_v3_ExtensionWithMatcher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_envoy_extensions_common_matching_v3_ExtensionWithMatcher_descriptor,
        new java.lang.String[] { "Matcher", "ExtensionConfig", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(udpa.annotations.Status.fileStatus);
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.envoy.config.common.matcher.v3.MatcherProto.getDescriptor();
    io.envoyproxy.envoy.config.core.v3.ExtensionProto.getDescriptor();
    udpa.annotations.Migrate.getDescriptor();
    udpa.annotations.Status.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
